# Generated by Django 3.2 on 2021-06-12 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Title',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
