# Generated by Django 3.2 on 2021-06-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210616_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
    ]
