# Generated by Django 3.2 on 2021-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_search_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='MaxPrice',
            field=models.DecimalField(decimal_places=0, max_digits=27, verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='MinPrice',
            field=models.DecimalField(decimal_places=0, max_digits=27, verbose_name='Minimum Price'),
        ),
    ]
